// catalogo.js — Fuente única de verdad del catálogo de 50 artefactos
// Todos los datos necesarios para la galería, las páginas SEO individuales y el sitemap

export const CATALOGO = [
  // ═══════════════════════════════════════
  // DIVERSIÓN (10)
  // ═══════════════════════════════════════
  {
    id: "oraculo",
    slug: "oraculo",
    categoria: "diversion",
    ruta: "artefactos/diversion/oraculo/",
    icono: "🔮",
    color: "var(--cat-diversion)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "El Oráculo de Delfos",
    nombre_en: "The Oracle of Delphi",
    desc_es: "Consulta a la Pitia. Verdad envuelta en misterio.",
    desc_en: "Consult the Pythia. Truth wrapped in mystery.",
    desc_larga_es: "El Oráculo de Delfos es una experiencia conversacional única donde la inteligencia artificial adopta el rol de la Pitia, la sacerdotisa del oráculo griego. Formula cualquier pregunta — sobre tu vida, el futuro, filosofía o el universo — y recibe una respuesta ambigua y poética, cargada de referencias mitológicas y sabiduría antigua. Cada consulta es única e irrepetible.",
    desc_larga_en: "The Oracle of Delphi is a unique conversational experience where artificial intelligence adopts the role of the Pythia, the priestess of the Greek oracle. Ask any question — about your life, the future, philosophy or the universe — and receive an ambiguous, poetic response filled with mythological references and ancient wisdom.",
    features_es: ["Respuestas proféticas con doble lectura", "Historial de consultas en sesión", "Efecto typewriter sobre mármol", "Bilingüe ES/EN"],
    features_en: ["Prophetic responses with double meaning", "Session consultation history", "Typewriter effect on marble", "Bilingual ES/EN"],
    paso_es: "Haz tu pregunta al Oráculo y recibe sabiduría envuelta en misterio",
    paso_en: "Ask the Oracle your question and receive wisdom wrapped in mystery",
    estado: "live"
  },
  {
    id: "musicsage",
    slug: "musicsage",
    categoria: "diversion",
    ruta: "artefactos/diversion/musicsage/",
    icono: "🎵",
    color: "var(--cat-diversion)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "MusicSage",
    nombre_en: "MusicSage",
    desc_es: "Teoría musical, historia y alma sonora.",
    desc_en: "Music theory, history and sonic soul.",
    desc_larga_es: "MusicSage es tu enciclopedia musical interactiva impulsada por IA. Pregunta sobre cualquier género, artista, teoría musical o movimiento sonoro y obtén respuestas profundas que conectan historia, técnica y emoción. Desde el barroco hasta el synthwave, MusicSage lo conoce todo.",
    desc_larga_en: "MusicSage is your AI-powered interactive music encyclopedia. Ask about any genre, artist, music theory or sonic movement and get deep answers connecting history, technique and emotion. From baroque to synthwave, MusicSage knows it all.",
    features_es: ["Conocimiento de todos los géneros musicales", "Historia y contexto cultural", "Teoría musical accesible", "Bilingüe ES/EN"],
    features_en: ["Knowledge of all music genres", "History and cultural context", "Accessible music theory", "Bilingual ES/EN"],
    paso_es: "Pregunta sobre música y recibe respuestas profundas conectando historia y emoción",
    paso_en: "Ask about music and get deep answers connecting history and emotion",
    estado: "live"
  },
  {
    id: "alquimista",
    slug: "alquimista",
    categoria: "diversion",
    ruta: "artefactos/diversion/alquimista/",
    icono: "⚗️",
    color: "var(--cat-diversion)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "El Alquimista",
    nombre_en: "The Alchemist",
    desc_es: "Filosofía hermética y ciencia antigua.",
    desc_en: "Hermetic philosophy and ancient science.",
    desc_larga_es: "El Alquimista fusiona filosofía hermética con ciencia antigua. Explora los misterios de la transmutación, los elementos y la Gran Obra a través de una IA que habla el lenguaje de los alquimistas medievales. Cada interacción revela capas de significado simbólico.",
    desc_larga_en: "The Alchemist fuses hermetic philosophy with ancient science. Explore the mysteries of transmutation, the elements and the Great Work through an AI that speaks the language of medieval alchemists. Each interaction reveals layers of symbolic meaning.",
    features_es: ["Filosofía hermética interactiva", "Referencias a textos alquímicos reales", "Lenguaje simbólico y evocador", "Bilingüe ES/EN"],
    features_en: ["Interactive hermetic philosophy", "References to real alchemical texts", "Symbolic and evocative language", "Bilingual ES/EN"],
    paso_es: "Explora la filosofía hermética y los misterios de la alquimia",
    paso_en: "Explore hermetic philosophy and the mysteries of alchemy",
    estado: "live"
  },
  {
    id: "duelo",
    slug: "duelo",
    categoria: "diversion",
    ruta: "artefactos/diversion/duelo/",
    icono: "⚔️",
    color: "var(--cat-diversion)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "Duelo de Filósofos",
    nombre_en: "Philosophers' Duel",
    desc_es: "Dos grandes mentes. Un tema. Tú decides.",
    desc_en: "Two great minds. One topic. You decide.",
    desc_larga_es: "Duelo de Filósofos enfrenta a dos grandes pensadores de la historia en un debate sobre el tema que tú elijas. Nietzsche vs Sócrates, Simone de Beauvoir vs Kant — la IA encarna sus estilos argumentativos y tú decides quién gana. Filosofía convertida en espectáculo intelectual.",
    desc_larga_en: "Philosophers' Duel pits two great thinkers from history against each other in a debate on the topic of your choice. Nietzsche vs Socrates, Simone de Beauvoir vs Kant — the AI embodies their argumentative styles and you decide who wins.",
    features_es: ["Debates entre filósofos históricos", "Tú eliges el tema del enfrentamiento", "Argumentos fieles al estilo de cada pensador", "Bilingüe ES/EN"],
    features_en: ["Debates between historical philosophers", "You choose the debate topic", "Arguments faithful to each thinker's style", "Bilingual ES/EN"],
    paso_es: "Elige dos filósofos, un tema, y observa el debate",
    paso_en: "Choose two philosophers, a topic, and watch the debate",
    estado: "live"
  },
  {
    id: "scriptorium",
    slug: "scriptorium",
    categoria: "diversion",
    ruta: "artefactos/diversion/scriptorium/",
    icono: "📜",
    color: "var(--cat-diversion)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "El Scriptorium",
    nombre_en: "The Scriptorium",
    desc_es: "Transforma texto en voz de otra época.",
    desc_en: "Transform text into the voice of another era.",
    desc_larga_es: "El Scriptorium transforma cualquier texto moderno en prosa de otra época. Pega un email, un tweet o un artículo y la IA lo reescribirá como si fuera un monje medieval, un cronista del Renacimiento o un periodista de la Belle Époque. El arte de escribir a través del tiempo.",
    desc_larga_en: "The Scriptorium transforms any modern text into prose from another era. Paste an email, a tweet or an article and the AI will rewrite it as if from a medieval monk, a Renaissance chronicler or a Belle Époque journalist. The art of writing through time.",
    features_es: ["Transformación a múltiples épocas históricas", "Fidelidad al estilo de cada período", "Funciona con cualquier tipo de texto", "Bilingüe ES/EN"],
    features_en: ["Transformation to multiple historical eras", "Faithful to each period's style", "Works with any type of text", "Bilingual ES/EN"],
    paso_es: "Pega tu texto, elige una época y observa la transformación",
    paso_en: "Paste your text, choose an era and watch the transformation",
    estado: "live"
  },
  {
    id: "maquina-tiempo",
    slug: "maquina-tiempo",
    categoria: "diversion",
    ruta: "artefactos/diversion/maquina-tiempo/",
    icono: "⏱️",
    color: "var(--cat-diversion)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "Máquina del Tiempo",
    nombre_en: "Time Machine",
    desc_es: "Elige una época y vívela en tiempo real.",
    desc_en: "Choose an era and live it in real time.",
    desc_larga_es: "La Máquina del Tiempo te transporta a cualquier momento de la historia. Elige un año, un lugar y un rol, y la IA construirá una narrativa inmersiva donde tomarás decisiones en tiempo real. Vive la caída de Roma, el descubrimiento de América o la llegada a la Luna como si estuvieras allí.",
    desc_larga_en: "The Time Machine transports you to any moment in history. Choose a year, a place and a role, and the AI will build an immersive narrative where you'll make decisions in real time. Experience the fall of Rome, the discovery of America or the Moon landing as if you were there.",
    features_es: ["Narrativa inmersiva en cualquier época", "Decisiones interactivas en tiempo real", "Fidelidad histórica detallada", "Bilingüe ES/EN"],
    features_en: ["Immersive narrative in any era", "Interactive real-time decisions", "Detailed historical accuracy", "Bilingual ES/EN"],
    paso_es: "Elige una época, un lugar y un rol para vivir la historia",
    paso_en: "Choose an era, a place and a role to live history",
    estado: "live"
  },
  {
    id: "bestiario",
    slug: "bestiario",
    categoria: "diversion",
    ruta: "artefactos/diversion/bestiario/",
    icono: "🐉",
    color: "var(--cat-diversion)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "Bestiario Digital",
    nombre_en: "Digital Bestiary",
    desc_es: "Criaturas mitológicas. Su lore, poder y leyenda.",
    desc_en: "Mythological creatures. Their lore and legend.",
    desc_larga_es: "El Bestiario Digital es una enciclopedia interactiva de criaturas mitológicas de todas las culturas. Descubre el lore, los poderes y las leyendas de dragones, quimeras, wendigos y cientos de seres fantásticos. La IA genera fichas detalladas con mitología comparada entre civilizaciones.",
    desc_larga_en: "The Digital Bestiary is an interactive encyclopedia of mythological creatures from all cultures. Discover the lore, powers and legends of dragons, chimeras, wendigos and hundreds of fantastic beings. The AI generates detailed cards with comparative mythology across civilizations.",
    features_es: ["Criaturas de todas las mitologías", "Fichas detalladas con poderes y leyendas", "Mitología comparada entre culturas", "Bilingüe ES/EN"],
    features_en: ["Creatures from all mythologies", "Detailed cards with powers and legends", "Comparative mythology across cultures", "Bilingual ES/EN"],
    paso_es: "Busca una criatura o deja que el bestiario te sorprenda",
    paso_en: "Search for a creature or let the bestiary surprise you",
    estado: "live"
  },
  {
    id: "sinfonia",
    slug: "sinfonia",
    categoria: "diversion",
    ruta: "artefactos/diversion/sinfonia/",
    icono: "🎼",
    color: "var(--cat-diversion)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "Sinfonía Generativa",
    nombre_en: "Generative Symphony",
    desc_es: "La IA compone. El canvas interpreta.",
    desc_en: "The AI composes. The canvas interprets.",
    desc_larga_es: "Sinfonía Generativa convierte descripciones textuales en composiciones musicales conceptuales. La IA genera una partitura narrativa que el canvas visual interpreta en tiempo real con formas, colores y movimiento. Una experiencia sinestésica donde el texto se convierte en música visual.",
    desc_larga_en: "Generative Symphony converts textual descriptions into conceptual musical compositions. The AI generates a narrative score that the visual canvas interprets in real time with shapes, colors and movement. A synesthetic experience where text becomes visual music.",
    features_es: ["Composición musical conceptual con IA", "Visualización en canvas en tiempo real", "Experiencia sinestésica única", "Bilingüe ES/EN"],
    features_en: ["Conceptual music composition with AI", "Real-time canvas visualization", "Unique synesthetic experience", "Bilingual ES/EN"],
    paso_es: "Describe una emoción o escena y observa la sinfonía visual",
    paso_en: "Describe an emotion or scene and watch the visual symphony",
    estado: "live"
  },
  {
    id: "detective",
    slug: "detective",
    categoria: "diversion",
    ruta: "artefactos/diversion/detective/",
    icono: "🔍",
    color: "var(--cat-diversion)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "El Detective",
    nombre_en: "The Detective",
    desc_es: "Resuelve crímenes con un detective de los años 40.",
    desc_en: "Solve crimes with a 1940s hard-boiled detective.",
    desc_larga_es: "El Detective te sumerge en una novela negra interactiva ambientada en los años 40. Un detective duro y cínico te guía por escenas del crimen, pistas y sospechosos. Tú tomas las decisiones — interrogas testigos, analizas pruebas y resuelves el caso. Cada partida es un misterio nuevo.",
    desc_larga_en: "The Detective immerses you in an interactive noir novel set in the 1940s. A hard-boiled, cynical detective guides you through crime scenes, clues and suspects. You make the decisions — interrogate witnesses, analyze evidence and solve the case.",
    features_es: ["Novela negra interactiva", "Generación procedimental de casos", "Decisiones que alteran la trama", "Bilingüe ES/EN"],
    features_en: ["Interactive noir novel", "Procedural case generation", "Decisions that alter the plot", "Bilingual ES/EN"],
    paso_es: "Investiga la escena del crimen y resuelve el caso",
    paso_en: "Investigate the crime scene and solve the case",
    estado: "live"
  },
  {
    id: "trivia",
    slug: "trivia",
    categoria: "diversion",
    ruta: "artefactos/diversion/trivia/",
    icono: "🧩",
    color: "var(--cat-diversion)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "Trivia Imposible",
    nombre_en: "Impossible Trivia",
    desc_es: "Preguntas que nadie debería saber responder.",
    desc_en: "Questions nobody should be able to answer.",
    desc_larga_es: "Trivia Imposible genera preguntas de conocimiento general tan específicas y oscuras que desafían incluso a los más eruditos. La dificultad se adapta a tus respuestas. Conecta datos de historia, ciencia, arte y cultura pop de formas que nunca imaginaste.",
    desc_larga_en: "Impossible Trivia generates general knowledge questions so specific and obscure they challenge even the most learned. Difficulty adapts to your answers. Connect facts from history, science, art and pop culture in ways you never imagined.",
    features_es: ["Preguntas ultra-específicas generadas por IA", "Dificultad adaptativa", "Conexiones inesperadas entre temas", "Bilingüe ES/EN"],
    features_en: ["Ultra-specific AI-generated questions", "Adaptive difficulty", "Unexpected connections between topics", "Bilingual ES/EN"],
    paso_es: "Responde preguntas cada vez más imposibles",
    paso_en: "Answer increasingly impossible questions",
    estado: "live"
  },

  // ═══════════════════════════════════════
  // PRODUCTIVIDAD (10)
  // ═══════════════════════════════════════
  {
    id: "redactor-emails",
    slug: "redactor-emails",
    categoria: "productividad",
    ruta: "artefactos/productividad/redactor-emails/",
    icono: "✉️",
    color: "var(--cat-productividad)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Redactor de emails",
    nombre_en: "Email Writer",
    desc_es: "Emails profesionales en segundos.",
    desc_en: "Professional emails in seconds.",
    desc_larga_es: "El Redactor de Emails genera correos electrónicos profesionales al instante. Describe el contexto, elige el tono y el destinatario, y obtén un email completo con asunto, saludo, cuerpo y despedida. Perfecto para comunicaciones de trabajo que necesitan el tono exacto.",
    desc_larga_en: "The Email Writer generates professional emails instantly. Describe the context, choose the tone and recipient, and get a complete email with subject, greeting, body and sign-off. Perfect for work communications that need the exact right tone.",
    features_es: ["5 tonos disponibles: formal, cercano, persuasivo, directo, cordial", "Email completo con asunto y estructura", "Contexto personalizado por destinatario", "Bilingüe ES/EN"],
    features_en: ["5 available tones: formal, friendly, persuasive, direct, cordial", "Complete email with subject and structure", "Personalized context per recipient", "Bilingual ES/EN"],
    paso_es: "Describe el contexto, elige tono y destinatario",
    paso_en: "Describe the context, choose tone and recipient",
    estado: "live"
  },
  {
    id: "resumidor",
    slug: "resumidor",
    categoria: "productividad",
    ruta: "artefactos/productividad/resumidor/",
    icono: "📋",
    color: "var(--cat-productividad)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Resumidor de texto",
    nombre_en: "Text Summarizer",
    desc_es: "Pega cualquier texto. Obtén lo esencial.",
    desc_en: "Paste any text. Get the essentials.",
    desc_larga_es: "El Resumidor de Texto condensa cualquier contenido en su esencia. Pega artículos, documentos, reportes o emails largos y obtén un resumen adaptado a tu necesidad: breve (3 frases), medio (1 párrafo) o detallado (con bullets). Ahorra tiempo sin perder lo importante.",
    desc_larga_en: "The Text Summarizer condenses any content to its essence. Paste articles, documents, reports or long emails and get a summary adapted to your needs: brief (3 sentences), medium (1 paragraph) or detailed (with bullets). Save time without losing what matters.",
    features_es: ["3 niveles de resumen: breve, medio, detallado", "Funciona con cualquier tipo de texto", "Extracción de puntos clave", "Bilingüe ES/EN"],
    features_en: ["3 summary levels: brief, medium, detailed", "Works with any text type", "Key point extraction", "Bilingual ES/EN"],
    paso_es: "Pega tu texto y elige el nivel de detalle del resumen",
    paso_en: "Paste your text and choose the summary detail level",
    estado: "live"
  },
  {
    id: "generador-tareas",
    slug: "generador-tareas",
    categoria: "productividad",
    ruta: "artefactos/productividad/generador-tareas/",
    icono: "✅",
    color: "var(--cat-productividad)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Generador de tareas",
    nombre_en: "Task Generator",
    desc_es: "De objetivo vago a lista de acción concreta.",
    desc_en: "From vague goal to concrete action list.",
    desc_larga_es: "El Generador de Tareas transforma objetivos vagos en listas de acción concretas. Describe lo que quieres lograr y la IA generará un desglose en tareas accionables con subtareas y dependencias. Tres niveles: simple (5 tareas), detallado (10 con subtareas) o épico (15 con dependencias).",
    desc_larga_en: "The Task Generator transforms vague objectives into concrete action lists. Describe what you want to achieve and the AI will generate a breakdown into actionable tasks with subtasks and dependencies. Three levels: simple (5 tasks), detailed (10 with subtasks) or epic (15 with dependencies).",
    features_es: ["3 niveles de granularidad", "Subtareas y dependencias", "Checklist interactiva", "Bilingüe ES/EN"],
    features_en: ["3 granularity levels", "Subtasks and dependencies", "Interactive checklist", "Bilingual ES/EN"],
    paso_es: "Describe tu objetivo y elige el nivel de detalle",
    paso_en: "Describe your goal and choose the detail level",
    estado: "live"
  },
  {
    id: "mejorador-prompts",
    slug: "mejorador-prompts",
    categoria: "productividad",
    ruta: "artefactos/productividad/mejorador-prompts/",
    icono: "✨",
    color: "var(--cat-productividad)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Mejorador de prompts",
    nombre_en: "Prompt Improver",
    desc_es: "Tu prompt, pero 10 veces más preciso.",
    desc_en: "Your prompt, but 10x more precise.",
    desc_larga_es: "El Mejorador de Prompts toma tus instrucciones para IA y las transforma en prompts precisos y efectivos. Muestra antes/después con análisis de las mejoras. Optimizado para GPT, Claude, Llama o uso general. Aprende prompt engineering viendo cómo se reescriben tus propios prompts.",
    desc_larga_en: "The Prompt Improver takes your AI instructions and transforms them into precise, effective prompts. Shows before/after with improvement analysis. Optimized for GPT, Claude, Llama or general use. Learn prompt engineering by watching your own prompts get rewritten.",
    features_es: ["Comparación antes/después", "Optimizado para GPT, Claude, Llama", "Análisis de mejoras aplicadas", "Bilingüe ES/EN"],
    features_en: ["Before/after comparison", "Optimized for GPT, Claude, Llama", "Analysis of applied improvements", "Bilingual ES/EN"],
    paso_es: "Pega tu prompt original y elige el modelo objetivo",
    paso_en: "Paste your original prompt and choose the target model",
    estado: "live"
  },
  {
    id: "traductor-tono",
    slug: "traductor-tono",
    categoria: "productividad",
    ruta: "artefactos/productividad/traductor-tono/",
    icono: "🎭",
    color: "var(--cat-productividad)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Traductor de tono",
    nombre_en: "Tone Translator",
    desc_es: "Formal, casual, persuasivo, empático. Tú eliges.",
    desc_en: "Formal, casual, persuasive, empathetic. You choose.",
    desc_larga_es: "El Traductor de Tono reescribe cualquier texto adaptándolo al tono que necesitas. Un mismo mensaje puede sonar formal para un informe, cercano para un colega, persuasivo para una venta o empático para una situación delicada. 6 tonos disponibles para cualquier situación.",
    desc_larga_en: "The Tone Translator rewrites any text adapting it to the tone you need. The same message can sound formal for a report, friendly for a colleague, persuasive for a sale or empathetic for a delicate situation. 6 tones available for any situation.",
    features_es: ["6 tonos: formal, casual, persuasivo, empático, profesional, divertido", "Mantiene el significado original", "Funciona con cualquier longitud de texto", "Bilingüe ES/EN"],
    features_en: ["6 tones: formal, casual, persuasive, empathetic, professional, fun", "Preserves original meaning", "Works with any text length", "Bilingual ES/EN"],
    paso_es: "Pega tu texto y elige el tono deseado",
    paso_en: "Paste your text and choose the desired tone",
    estado: "live"
  },
  {
    id: "planificador",
    slug: "planificador",
    categoria: "productividad",
    ruta: "artefactos/productividad/planificador/",
    icono: "📅",
    color: "var(--cat-productividad)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Planificador semanal",
    nombre_en: "Weekly Planner",
    desc_es: "Organiza tu semana con ayuda de la IA.",
    desc_en: "Organize your week with AI help.",
    desc_larga_es: "El Planificador Semanal organiza tu semana en base a tus objetivos, compromisos y restricciones. La IA genera un plan estructurado de 7 días con bloques de mañana, tarde y noche. Elige la intensidad: relajada, equilibrada o intensiva. Visualiza todo en un grid interactivo.",
    desc_larga_en: "The Weekly Planner organizes your week based on your goals, commitments and constraints. The AI generates a structured 7-day plan with morning, afternoon and evening blocks. Choose intensity: relaxed, balanced or intensive. View everything in an interactive grid.",
    features_es: ["Plan de 7 días con bloques horarios", "3 intensidades: relajada, equilibrada, intensiva", "Grid visual interactivo", "Bilingüe ES/EN"],
    features_en: ["7-day plan with time blocks", "3 intensities: relaxed, balanced, intensive", "Interactive visual grid", "Bilingual ES/EN"],
    paso_es: "Describe tus objetivos y compromisos de la semana",
    paso_en: "Describe your goals and commitments for the week",
    estado: "live"
  },
  {
    id: "feedback-cv",
    slug: "feedback-cv",
    categoria: "productividad",
    ruta: "artefactos/productividad/feedback-cv/",
    icono: "📄",
    color: "var(--cat-productividad)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Feedback de CV",
    nombre_en: "CV Feedback",
    desc_es: "Análisis directo de tu currículum.",
    desc_en: "Direct analysis of your resume.",
    desc_larga_es: "Feedback de CV analiza tu currículum con ojo experto. Pega el texto de tu CV, indica el puesto objetivo y recibe un análisis con puntuación, fortalezas, debilidades y sugerencias concretas de mejora. Tres niveles de profundidad: rápido, completo o experto con reescrituras.",
    desc_larga_en: "CV Feedback analyzes your resume with an expert eye. Paste your CV text, indicate the target position and receive an analysis with scoring, strengths, weaknesses and specific improvement suggestions. Three depth levels: quick, complete or expert with rewrites.",
    features_es: ["Puntuación de 1 a 10", "Fortalezas y debilidades identificadas", "Sugerencias concretas de mejora", "Bilingüe ES/EN"],
    features_en: ["Score from 1 to 10", "Identified strengths and weaknesses", "Specific improvement suggestions", "Bilingual ES/EN"],
    paso_es: "Pega tu CV e indica el puesto al que aspiras",
    paso_en: "Paste your CV and indicate the target position",
    estado: "live"
  },
  {
    id: "carta-presentacion",
    slug: "carta-presentacion",
    categoria: "productividad",
    ruta: "artefactos/productividad/carta-presentacion/",
    icono: "💼",
    color: "var(--cat-productividad)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Carta de presentación",
    nombre_en: "Cover Letter",
    desc_es: "Personalizada, sin clichés, lista para enviar.",
    desc_en: "Personalized, cliché-free, ready to send.",
    desc_larga_es: "Genera cartas de presentación personalizadas que realmente funcionan. Indica el puesto, la empresa, tu experiencia y habilidades clave, y la IA creará una carta sin clichés, con gancho real y estructura profesional. Tres tonos: profesional, cercano o audaz.",
    desc_larga_en: "Generate personalized cover letters that actually work. Indicate the position, company, your experience and key skills, and the AI will create a cliché-free letter with real hooks and professional structure. Three tones: professional, friendly or bold.",
    features_es: ["3 tonos: profesional, cercano, audaz", "Sin clichés genéricos", "Personalizada con datos reales", "Bilingüe ES/EN"],
    features_en: ["3 tones: professional, friendly, bold", "No generic clichés", "Personalized with real data", "Bilingual ES/EN"],
    paso_es: "Indica puesto, empresa y tu experiencia clave",
    paso_en: "Indicate position, company and your key experience",
    estado: "live"
  },
  {
    id: "simplificador-legal",
    slug: "simplificador-legal",
    categoria: "productividad",
    ruta: "artefactos/productividad/simplificador-legal/",
    icono: "⚖️",
    color: "var(--cat-productividad)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Simplificador legal",
    nombre_en: "Legal Simplifier",
    desc_es: "Traduce contratos y documentos legales a español claro.",
    desc_en: "Translates contracts to plain language.",
    desc_larga_es: "El Simplificador Legal traduce contratos, términos de servicio y documentos legales a un lenguaje humano claro. Identifica cláusulas importantes, advierte sobre condiciones inusuales y desglosa el texto cláusula por cláusula si lo necesitas. Tu abogado digital de bolsillo.",
    desc_larga_en: "The Legal Simplifier translates contracts, terms of service and legal documents into clear human language. Identifies important clauses, warns about unusual conditions and breaks down text clause by clause if needed. Your pocket digital lawyer.",
    features_es: ["3 niveles: resumen, explicación, cláusula a cláusula", "Alertas para cláusulas importantes", "Lenguaje claro y accesible", "Bilingüe ES/EN"],
    features_en: ["3 levels: summary, explanation, clause by clause", "Alerts for important clauses", "Clear and accessible language", "Bilingual ES/EN"],
    paso_es: "Pega el texto legal y elige el nivel de detalle",
    paso_en: "Paste the legal text and choose the detail level",
    estado: "live"
  },
  {
    id: "asistente-reuniones",
    slug: "asistente-reuniones",
    categoria: "productividad",
    ruta: "artefactos/productividad/asistente-reuniones/",
    icono: "🎙️",
    color: "var(--cat-productividad)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Asistente de reuniones",
    nombre_en: "Meeting Assistant",
    desc_es: "Actas, resúmenes y próximos pasos al instante.",
    desc_en: "Minutes, summaries and next steps instantly.",
    desc_larga_es: "El Asistente de Reuniones transforma tus notas o transcripciones en documentos profesionales al instante. Genera actas formales, resúmenes ejecutivos o listas de próximos pasos con responsables. Tres formatos adaptados a cada necesidad.",
    desc_larga_en: "The Meeting Assistant transforms your notes or transcripts into professional documents instantly. Generates formal minutes, executive summaries or next-steps lists with assignees. Three formats adapted to each need.",
    features_es: ["3 formatos: acta, resumen ejecutivo, próximos pasos", "Identifica decisiones y responsables", "Funciona con notas informales", "Bilingüe ES/EN"],
    features_en: ["3 formats: minutes, executive summary, next steps", "Identifies decisions and assignees", "Works with informal notes", "Bilingual ES/EN"],
    paso_es: "Pega tus notas de la reunión y elige el formato de salida",
    paso_en: "Paste your meeting notes and choose the output format",
    estado: "live"
  },

  // ═══════════════════════════════════════
  // RESEARCH (10)
  // ═══════════════════════════════════════
  {
    id: "mapa-ideas",
    slug: "mapa-ideas",
    categoria: "research",
    ruta: "artefactos/diversion/mapa-ideas/",
    icono: "🕸️",
    color: "var(--cat-research)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Mapa de Ideas",
    nombre_en: "Map of Ideas",
    desc_es: "Grafo interactivo de conceptos. Explora con un clic.",
    desc_en: "Interactive concept graph. Explore with one click.",
    desc_larga_es: "El Mapa de Ideas genera grafos interactivos de conceptos conectados. Introduce un tema y la IA construirá una red visual de ideas relacionadas que puedes explorar con un clic. Cada nodo expande nuevas conexiones, creando un mapa de conocimiento infinito.",
    desc_larga_en: "The Map of Ideas generates interactive graphs of connected concepts. Enter a topic and the AI will build a visual network of related ideas you can explore with one click. Each node expands new connections, creating an infinite knowledge map.",
    features_es: ["Grafo visual interactivo", "Expansión infinita de conceptos", "Conexiones inesperadas entre temas", "Bilingüe ES/EN"],
    features_en: ["Interactive visual graph", "Infinite concept expansion", "Unexpected connections between topics", "Bilingual ES/EN"],
    paso_es: "Introduce un tema y explora el mapa de conexiones",
    paso_en: "Enter a topic and explore the connection map",
    estado: "live"
  },
  {
    id: "gabinete-objetos",
    slug: "gabinete-objetos",
    categoria: "research",
    ruta: "artefactos/diversion/gabinete-objetos/",
    icono: "🏺",
    color: "var(--cat-research)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Gabinete de Objetos",
    nombre_en: "Cabinet of Objects",
    desc_es: "Objetos raros reales de la historia.",
    desc_en: "Real rare objects from history.",
    desc_larga_es: "El Gabinete de Objetos es un museo virtual de curiosidades históricas reales. La IA genera fichas detalladas de objetos raros y fascinantes: desde el mecanismo de Antikythera hasta la esfera de Betz. Cada objeto incluye historia verificada, contexto cultural y datos sorprendentes.",
    desc_larga_en: "The Cabinet of Objects is a virtual museum of real historical curiosities. The AI generates detailed cards of rare and fascinating objects: from the Antikythera mechanism to the Betz sphere. Each object includes verified history, cultural context and surprising facts.",
    features_es: ["Objetos históricos reales verificados", "Fichas detalladas con contexto cultural", "Datos curiosos y sorprendentes", "Bilingüe ES/EN"],
    features_en: ["Verified real historical objects", "Detailed cards with cultural context", "Curious and surprising facts", "Bilingual ES/EN"],
    paso_es: "Descubre objetos raros de la historia con fichas detalladas",
    paso_en: "Discover rare historical objects with detailed cards",
    estado: "live"
  },
  {
    id: "comparador",
    slug: "comparador",
    categoria: "research",
    ruta: "artefactos/research/comparador/",
    icono: "⚖️",
    color: "var(--cat-research)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Comparador de conceptos",
    nombre_en: "Concept Comparator",
    desc_es: "Dos ideas enfrentadas. Similitudes y diferencias.",
    desc_en: "Two ideas face to face. Similarities and differences.",
    desc_larga_es: "El Comparador de Conceptos enfrenta dos ideas, teorías, tecnologías o cualquier par de conceptos y genera un análisis estructurado de similitudes, diferencias, ventajas y desventajas. Perfecto para tomar decisiones informadas o entender matices entre conceptos relacionados.",
    desc_larga_en: "The Concept Comparator pits two ideas, theories, technologies or any pair of concepts against each other and generates a structured analysis of similarities, differences, advantages and disadvantages. Perfect for making informed decisions.",
    features_es: ["Análisis estructurado de similitudes y diferencias", "Tabla comparativa visual", "Funciona con cualquier par de conceptos", "Bilingüe ES/EN"],
    features_en: ["Structured analysis of similarities and differences", "Visual comparison table", "Works with any pair of concepts", "Bilingual ES/EN"],
    paso_es: "Introduce dos conceptos y obtén un análisis comparativo",
    paso_en: "Enter two concepts and get a comparative analysis",
    estado: "live"
  },
  {
    id: "dafo",
    slug: "dafo",
    categoria: "research",
    ruta: "artefactos/research/dafo/",
    icono: "📊",
    color: "var(--cat-research)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Análisis DAFO",
    nombre_en: "SWOT Analysis",
    desc_es: "Fortalezas, debilidades, oportunidades y amenazas.",
    desc_en: "Strengths, weaknesses, opportunities and threats.",
    desc_larga_es: "El Análisis DAFO genera matrices DAFO completas para cualquier proyecto, idea de negocio o decisión estratégica. La IA identifica fortalezas, debilidades, oportunidades y amenazas con profundidad analítica, presentadas en un formato visual claro y accionable.",
    desc_larga_en: "The SWOT Analysis generates complete SWOT matrices for any project, business idea or strategic decision. The AI identifies strengths, weaknesses, opportunities and threats with analytical depth, presented in a clear, actionable visual format.",
    features_es: ["Matriz DAFO visual completa", "Profundidad analítica real", "Funciona con cualquier proyecto o decisión", "Bilingüe ES/EN"],
    features_en: ["Complete visual SWOT matrix", "Real analytical depth", "Works with any project or decision", "Bilingual ES/EN"],
    paso_es: "Describe tu proyecto o decisión para generar el análisis DAFO",
    paso_en: "Describe your project or decision to generate the SWOT analysis",
    estado: "live"
  },
  {
    id: "detector-sesgos",
    slug: "detector-sesgos",
    categoria: "research",
    ruta: "artefactos/research/detector-sesgos/",
    icono: "🔬",
    color: "var(--cat-research)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Detector de sesgos",
    nombre_en: "Bias Detector",
    desc_es: "Identifica sesgos cognitivos en cualquier argumento.",
    desc_en: "Identify cognitive biases in any argument.",
    desc_larga_es: "El Detector de Sesgos analiza textos, argumentos o noticias para identificar sesgos cognitivos presentes. Desde el sesgo de confirmación hasta la falacia del hombre de paja, la IA señala exactamente dónde aparece cada sesgo y explica cómo afecta al razonamiento.",
    desc_larga_en: "The Bias Detector analyzes texts, arguments or news to identify cognitive biases present. From confirmation bias to the straw man fallacy, the AI points out exactly where each bias appears and explains how it affects reasoning.",
    features_es: ["Detecta múltiples sesgos cognitivos", "Señala la ubicación exacta en el texto", "Explicaciones claras de cada sesgo", "Bilingüe ES/EN"],
    features_en: ["Detects multiple cognitive biases", "Points to exact location in text", "Clear explanations of each bias", "Bilingual ES/EN"],
    paso_es: "Pega un argumento o texto para detectar sesgos",
    paso_en: "Paste an argument or text to detect biases",
    estado: "live"
  },
  {
    id: "contraargumentador",
    slug: "contraargumentador",
    categoria: "research",
    ruta: "artefactos/research/contraargumentador/",
    icono: "🗣️",
    color: "var(--cat-research)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Contraargumentador",
    nombre_en: "Counterarguer",
    desc_es: "El mejor abogado del diablo para tus ideas.",
    desc_en: "The best devil's advocate for your ideas.",
    desc_larga_es: "El Contraargumentador actúa como el abogado del diablo más inteligente para tus ideas. Presenta tu argumento, tesis o plan y recibe contraargumentos sólidos, objeciones fundamentadas y puntos ciegos que quizás no habías considerado. La herramienta perfecta para fortalecer tus ideas.",
    desc_larga_en: "The Counterarguer acts as the smartest devil's advocate for your ideas. Present your argument, thesis or plan and receive solid counterarguments, grounded objections and blind spots you may not have considered. The perfect tool to strengthen your ideas.",
    features_es: ["Contraargumentos sólidos y fundamentados", "Identifica puntos ciegos", "Fortalece tus argumentos", "Bilingüe ES/EN"],
    features_en: ["Solid, grounded counterarguments", "Identifies blind spots", "Strengthens your arguments", "Bilingual ES/EN"],
    paso_es: "Presenta tu argumento y recibe contraargumentos",
    paso_en: "Present your argument and receive counterarguments",
    estado: "live"
  },
  {
    id: "linea-tiempo",
    slug: "linea-tiempo",
    categoria: "research",
    ruta: "artefactos/research/linea-tiempo/",
    icono: "📏",
    color: "var(--cat-research)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Línea de tiempo histórica",
    nombre_en: "Historical Timeline",
    desc_es: "Visualiza eventos en contexto cronológico.",
    desc_en: "Visualize events in chronological context.",
    desc_larga_es: "La Línea de Tiempo Histórica genera timelines visuales e interactivos sobre cualquier tema. Introduce un período, un concepto o un proceso y la IA creará una línea temporal con eventos clave, contexto y conexiones causales. Perfecto para investigación y estudio.",
    desc_larga_en: "The Historical Timeline generates visual, interactive timelines on any topic. Enter a period, concept or process and the AI will create a timeline with key events, context and causal connections. Perfect for research and study.",
    features_es: ["Timelines visuales interactivos", "Eventos con contexto y conexiones", "Funciona con cualquier tema o período", "Bilingüe ES/EN"],
    features_en: ["Interactive visual timelines", "Events with context and connections", "Works with any topic or period", "Bilingual ES/EN"],
    paso_es: "Introduce un tema o período para generar la línea temporal",
    paso_en: "Enter a topic or period to generate the timeline",
    estado: "live"
  },
  {
    id: "arbol-decision",
    slug: "arbol-decision",
    categoria: "research",
    ruta: "artefactos/research/arbol-decision/",
    icono: "🌳",
    color: "var(--cat-research)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Árbol de decisión",
    nombre_en: "Decision Tree",
    desc_es: "Estructura cualquier decisión compleja.",
    desc_en: "Structure any complex decision.",
    desc_larga_es: "El Árbol de Decisión estructura cualquier decisión compleja en un diagrama visual interactivo. Describe tu dilema y la IA generará un árbol con opciones, consecuencias, probabilidades y recomendaciones. Renderizado dinámico en Canvas para navegar por las ramas de decisión.",
    desc_larga_en: "The Decision Tree structures any complex decision into an interactive visual diagram. Describe your dilemma and the AI will generate a tree with options, consequences, probabilities and recommendations. Dynamic Canvas rendering to navigate decision branches.",
    features_es: ["Diagrama visual interactivo en Canvas", "Opciones con consecuencias y probabilidades", "Navegación por ramas de decisión", "Bilingüe ES/EN"],
    features_en: ["Interactive visual Canvas diagram", "Options with consequences and probabilities", "Navigate decision branches", "Bilingual ES/EN"],
    paso_es: "Describe tu decisión y navega por las opciones",
    paso_en: "Describe your decision and navigate the options",
    estado: "live"
  },
  {
    id: "analogias",
    slug: "analogias",
    categoria: "research",
    ruta: "artefactos/research/analogias/",
    icono: "🔗",
    color: "var(--cat-research)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Buscador de analogías",
    nombre_en: "Analogy Finder",
    desc_es: "Explica lo complejo con comparaciones perfectas.",
    desc_en: "Explain the complex with perfect comparisons.",
    desc_larga_es: "El Buscador de Analogías encuentra las comparaciones perfectas para explicar conceptos complejos. Introduce un tema difícil y la IA generará analogías desde múltiples dominios: cocina, deportes, naturaleza, tecnología. Ideal para enseñar, presentar o simplemente entender mejor las cosas.",
    desc_larga_en: "The Analogy Finder discovers the perfect comparisons to explain complex concepts. Enter a difficult topic and the AI will generate analogies from multiple domains: cooking, sports, nature, technology. Ideal for teaching, presenting or simply understanding things better.",
    features_es: ["Analogías desde múltiples dominios", "Explicaciones accesibles de temas complejos", "Ideal para enseñanza y presentaciones", "Bilingüe ES/EN"],
    features_en: ["Analogies from multiple domains", "Accessible explanations of complex topics", "Ideal for teaching and presentations", "Bilingual ES/EN"],
    paso_es: "Introduce un concepto complejo para encontrar analogías",
    paso_en: "Enter a complex concept to find analogies",
    estado: "live"
  },
  {
    id: "sintetizador",
    slug: "sintetizador",
    categoria: "research",
    ruta: "artefactos/research/sintetizador/",
    icono: "🧬",
    color: "var(--cat-research)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Sintetizador de debates",
    nombre_en: "Debate Synthesizer",
    desc_es: "Extrae las posturas clave de cualquier debate.",
    desc_en: "Extract key positions from any debate.",
    desc_larga_es: "El Sintetizador de Debates analiza cualquier controversia y extrae las posturas clave enfrentadas. Identifica los argumentos más fuertes de cada lado, los puntos de consenso y las áreas de desacuerdo irreductible. Perfecto para investigación, periodismo o formación de opinión.",
    desc_larga_en: "The Debate Synthesizer analyzes any controversy and extracts the key opposing positions. Identifies the strongest arguments on each side, consensus points and areas of irreducible disagreement. Perfect for research, journalism or opinion formation.",
    features_es: ["Extracción de posturas clave", "Argumentos fuertes de cada lado", "Puntos de consenso y desacuerdo", "Bilingüe ES/EN"],
    features_en: ["Key position extraction", "Strong arguments from each side", "Consensus and disagreement points", "Bilingual ES/EN"],
    paso_es: "Introduce un tema controvertido para sintetizar el debate",
    paso_en: "Enter a controversial topic to synthesize the debate",
    estado: "live"
  },

  // ═══════════════════════════════════════
  // CREATIVIDAD (10)
  // ═══════════════════════════════════════
  {
    id: "microrrelatos",
    slug: "microrrelatos",
    categoria: "creatividad",
    ruta: "artefactos/creatividad/microrrelatos/",
    icono: "✍️",
    color: "var(--cat-creatividad)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "Generador de microrrelatos",
    nombre_en: "Flash Fiction Generator",
    desc_es: "Historias completas en menos de 100 palabras.",
    desc_en: "Complete stories in under 100 words.",
    desc_larga_es: "El Generador de Microrrelatos crea historias completas en menos de 100 palabras a partir de una semilla creativa. Elige el tono (terror, humor, lírico, absurdo, romántico, melancólico) y el tipo de final (abierto, cerrado, twist). Cada historia es única e irrepetible.",
    desc_larga_en: "The Flash Fiction Generator creates complete stories in under 100 words from a creative seed. Choose the tone (horror, humor, lyrical, absurd, romantic, melancholic) and ending type (open, closed, twist). Each story is unique and unrepeatable.",
    features_es: ["6 tonos narrativos", "3 tipos de final", "Historial de sesión", "Bilingüe ES/EN"],
    features_en: ["6 narrative tones", "3 ending types", "Session history", "Bilingual ES/EN"],
    paso_es: "Dale una semilla creativa y elige tono y final",
    paso_en: "Give a creative seed and choose tone and ending",
    estado: "live"
  },
  {
    id: "taller-poesia",
    slug: "taller-poesia",
    categoria: "creatividad",
    ruta: "artefactos/creatividad/taller-poesia/",
    icono: "🖊️",
    color: "var(--cat-creatividad)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "Taller de poesía",
    nombre_en: "Poetry Workshop",
    desc_es: "Escribe, analiza y mejora poemas.",
    desc_en: "Write, analyze and improve poems.",
    desc_larga_es: "El Taller de Poesía es tu espacio creativo para escribir, analizar y mejorar poemas con IA. Genera poemas desde una temática, analiza la métrica y las figuras retóricas de tus versos, o recibe sugerencias de mejora. Múltiples estilos: soneto, haiku, verso libre y más.",
    desc_larga_en: "The Poetry Workshop is your creative space to write, analyze and improve poems with AI. Generate poems from a theme, analyze the metrics and rhetorical figures of your verses, or receive improvement suggestions. Multiple styles: sonnet, haiku, free verse and more.",
    features_es: ["Generación y análisis de poemas", "Múltiples estilos: soneto, haiku, verso libre", "Sugerencias de mejora", "Bilingüe ES/EN"],
    features_en: ["Poem generation and analysis", "Multiple styles: sonnet, haiku, free verse", "Improvement suggestions", "Bilingual ES/EN"],
    paso_es: "Escribe o genera un poema y recibe análisis",
    paso_en: "Write or generate a poem and receive analysis",
    estado: "live"
  },
  {
    id: "nombre-marca",
    slug: "nombre-marca",
    categoria: "creatividad",
    ruta: "artefactos/creatividad/nombre-marca/",
    icono: "💡",
    color: "var(--cat-creatividad)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Nombre de marca",
    nombre_en: "Brand Name Generator",
    desc_es: "Nombres únicos con su historia y concepto.",
    desc_en: "Unique names with their story and concept.",
    desc_larga_es: "El generador de Nombre de Marca crea nombres únicos y memorables para tu proyecto, empresa o producto. Cada propuesta incluye el razonamiento creativo, el significado y cómo funciona fonéticamente. Describe tu concepto y recibe opciones que realmente cuentan una historia.",
    desc_larga_en: "The Brand Name Generator creates unique and memorable names for your project, company or product. Each proposal includes the creative reasoning, meaning and how it works phonetically. Describe your concept and receive options that truly tell a story.",
    features_es: ["Nombres con razonamiento creativo", "Análisis fonético y semántico", "Múltiples propuestas por generación", "Bilingüe ES/EN"],
    features_en: ["Names with creative reasoning", "Phonetic and semantic analysis", "Multiple proposals per generation", "Bilingual ES/EN"],
    paso_es: "Describe tu proyecto o producto para generar nombres",
    paso_en: "Describe your project or product to generate names",
    estado: "live"
  },
  {
    id: "eslogan",
    slug: "eslogan",
    categoria: "creatividad",
    ruta: "artefactos/creatividad/eslogan/",
    icono: "📢",
    color: "var(--cat-creatividad)",
    categoria_schema: "BusinessApplication",
    nombre_es: "Eslogan creativo",
    nombre_en: "Creative Slogan",
    desc_es: "El gancho que hace que te recuerden.",
    desc_en: "The hook that makes you memorable.",
    desc_larga_es: "El generador de Eslogan Creativo produce lemas publicitarios memorables y efectivos. Describe tu marca, producto o servicio y recibe eslóganes con ritmo, gancho y significado. Cada propuesta explica la técnica retórica utilizada para que aprendas mientras creas.",
    desc_larga_en: "The Creative Slogan generator produces memorable and effective advertising taglines. Describe your brand, product or service and receive slogans with rhythm, hook and meaning. Each proposal explains the rhetorical technique used so you learn while creating.",
    features_es: ["Eslóganes con técnica retórica explicada", "Múltiples propuestas por generación", "Adaptado a tu marca y público", "Bilingüe ES/EN"],
    features_en: ["Slogans with explained rhetorical technique", "Multiple proposals per generation", "Adapted to your brand and audience", "Bilingual ES/EN"],
    paso_es: "Describe tu marca o producto para generar eslóganes",
    paso_en: "Describe your brand or product to generate slogans",
    estado: "live"
  },
  {
    id: "continuador",
    slug: "continuador",
    categoria: "creatividad",
    ruta: "artefactos/creatividad/continuador/",
    icono: "📖",
    color: "var(--cat-creatividad)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "Continuador de historias",
    nombre_en: "Story Continuer",
    desc_es: "Pega el inicio de tu historia. La IA la continúa.",
    desc_en: "Paste your story opening. AI continues it.",
    desc_larga_es: "El Continuador de Historias toma donde tú lo dejaste. Pega el inicio de tu historia, novela o guión, y la IA la continuará manteniendo tu voz, tono y estilo. Perfecto para romper bloqueos creativos o explorar nuevas direcciones narrativas.",
    desc_larga_en: "The Story Continuer picks up where you left off. Paste the beginning of your story, novel or script, and the AI will continue it maintaining your voice, tone and style. Perfect for breaking creative blocks or exploring new narrative directions.",
    features_es: ["Mantiene tu voz y estilo narrativo", "Múltiples continuaciones posibles", "Ideal para romper bloqueos creativos", "Bilingüe ES/EN"],
    features_en: ["Maintains your voice and narrative style", "Multiple possible continuations", "Ideal for breaking creative blocks", "Bilingual ES/EN"],
    paso_es: "Pega el inicio de tu historia para que la IA la continúe",
    paso_en: "Paste your story opening for the AI to continue it",
    estado: "live"
  },
  {
    id: "critico-literario",
    slug: "critico-literario",
    categoria: "creatividad",
    ruta: "artefactos/creatividad/critico-literario/",
    icono: "🎓",
    color: "var(--cat-creatividad)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Crítico literario",
    nombre_en: "Literary Critic",
    desc_es: "Análisis profundo de cualquier texto literario.",
    desc_en: "Deep analysis of any literary text.",
    desc_larga_es: "El Crítico Literario analiza cualquier texto con la profundidad de un profesor universitario. Pega un fragmento y recibe análisis de estructura narrativa, figuras retóricas, tono, simbolismo, intertextualidad y calidad literaria. Con sugerencias de mejora si es tu propia obra.",
    desc_larga_en: "The Literary Critic analyzes any text with the depth of a university professor. Paste a fragment and receive analysis of narrative structure, rhetorical figures, tone, symbolism, intertextuality and literary quality. With improvement suggestions if it's your own work.",
    features_es: ["Análisis de estructura y figuras retóricas", "Evaluación de tono y simbolismo", "Sugerencias de mejora para tu obra", "Bilingüe ES/EN"],
    features_en: ["Structure and rhetorical figure analysis", "Tone and symbolism evaluation", "Improvement suggestions for your work", "Bilingual ES/EN"],
    paso_es: "Pega un texto literario para recibir análisis profundo",
    paso_en: "Paste a literary text to receive deep analysis",
    estado: "live"
  },
  {
    id: "worldbuilder",
    slug: "worldbuilder",
    categoria: "creatividad",
    ruta: "artefactos/creatividad/worldbuilder/",
    icono: "🌍",
    color: "var(--cat-creatividad)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "Worldbuilder",
    nombre_en: "Worldbuilder",
    desc_es: "Construye mundos ficticios con coherencia interna.",
    desc_en: "Build fictional worlds with internal coherence.",
    desc_larga_es: "Worldbuilder te ayuda a construir mundos ficticios completos y coherentes. Describe la premisa de tu mundo — fantástico, sci-fi, post-apocalíptico — y la IA generará geografía, política, cultura, magia/tecnología y conflictos internos que encajen como un reloj.",
    desc_larga_en: "Worldbuilder helps you build complete, coherent fictional worlds. Describe your world's premise — fantasy, sci-fi, post-apocalyptic — and the AI will generate geography, politics, culture, magic/technology and internal conflicts that fit like clockwork.",
    features_es: ["Mundos completos con geografía y política", "Sistemas de magia o tecnología coherentes", "Conflictos internos generados", "Bilingüe ES/EN"],
    features_en: ["Complete worlds with geography and politics", "Coherent magic or technology systems", "Generated internal conflicts", "Bilingual ES/EN"],
    paso_es: "Describe la premisa de tu mundo para construirlo",
    paso_en: "Describe your world's premise to build it",
    estado: "live"
  },
  {
    id: "dialogo",
    slug: "dialogo",
    categoria: "creatividad",
    ruta: "artefactos/creatividad/dialogo/",
    icono: "💬",
    color: "var(--cat-creatividad)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "Diálogo de personajes",
    nombre_en: "Character Dialogue",
    desc_es: "Dos personajes. Una escena. Química instantánea.",
    desc_en: "Two characters. One scene. Instant chemistry.",
    desc_larga_es: "Diálogo de Personajes genera conversaciones naturales entre dos personajes que tú defines. Describe cada personaje, la escena y el conflicto, y la IA escribirá un diálogo con química real, subtexto y arco dramático. Perfecto para guionistas, novelistas o juegos narrativos.",
    desc_larga_en: "Character Dialogue generates natural conversations between two characters you define. Describe each character, the scene and the conflict, and the AI will write dialogue with real chemistry, subtext and dramatic arc. Perfect for screenwriters, novelists or narrative games.",
    features_es: ["Diálogos con química y subtexto", "Personajes definidos por ti", "Arco dramático natural", "Bilingüe ES/EN"],
    features_en: ["Dialogue with chemistry and subtext", "Characters defined by you", "Natural dramatic arc", "Bilingual ES/EN"],
    paso_es: "Define dos personajes y una escena para generar el diálogo",
    paso_en: "Define two characters and a scene to generate dialogue",
    estado: "live"
  },
  {
    id: "reescritor",
    slug: "reescritor",
    categoria: "creatividad",
    ruta: "artefactos/creatividad/reescritor/",
    icono: "🔄",
    color: "var(--cat-creatividad)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "Reescribidor de escenas",
    nombre_en: "Scene Rewriter",
    desc_es: "La misma escena en 5 estilos distintos.",
    desc_en: "The same scene in 5 different styles.",
    desc_larga_es: "El Reescribidor de Escenas toma una escena o fragmento y lo reescribe en 5 estilos literarios diferentes. Desde minimalismo tipo Hemingway hasta barroco tipo García Márquez, pasando por thriller, comedia y poesía. Descubre cómo el estilo transforma completamente una historia.",
    desc_larga_en: "The Scene Rewriter takes a scene or fragment and rewrites it in 5 different literary styles. From Hemingway-style minimalism to García Márquez-style baroque, through thriller, comedy and poetry. Discover how style completely transforms a story.",
    features_es: ["5 reescrituras en estilos diferentes", "Aprende sobre estilos literarios", "Funciona con cualquier escena o fragmento", "Bilingüe ES/EN"],
    features_en: ["5 rewrites in different styles", "Learn about literary styles", "Works with any scene or fragment", "Bilingual ES/EN"],
    paso_es: "Pega una escena y descubre cómo suena en 5 estilos",
    paso_en: "Paste a scene and discover how it sounds in 5 styles",
    estado: "live"
  },
  {
    id: "saga",
    slug: "saga",
    categoria: "creatividad",
    ruta: "artefactos/creatividad/saga/",
    icono: "📖",
    color: "var(--cat-creatividad)",
    categoria_schema: "EntertainmentApplication",
    nombre_es: "Generador de sagas",
    nombre_en: "Saga Generator",
    desc_es: "Trilogías completas con portadas, sinopsis y continuación.",
    desc_en: "Complete trilogies with covers, synopses and continuation.",
    desc_larga_es: "El Generador de Sagas crea trilogías completas a partir de una idea. Cada libro incluye título, portada conceptual, sinopsis detallada y personajes principales. Elige entre múltiples géneros: fantasía, ciencia ficción, thriller, romance épico, histórica o terror.",
    desc_larga_en: "The Saga Generator creates complete trilogies from an idea. Each book includes title, conceptual cover, detailed synopsis and main characters. Choose from multiple genres: fantasy, sci-fi, thriller, epic romance, historical or horror.",
    features_es: ["Trilogías completas con sinopsis", "Portadas conceptuales generadas", "6 géneros disponibles", "Bilingüe ES/EN"],
    features_en: ["Complete trilogies with synopses", "Generated conceptual covers", "6 available genres", "Bilingual ES/EN"],
    paso_es: "Describe tu idea y elige el género para tu trilogía",
    paso_en: "Describe your idea and choose the genre for your trilogy",
    estado: "live"
  },

  // ═══════════════════════════════════════
  // EDUCACIÓN (10)
  // ═══════════════════════════════════════
  {
    id: "explicador",
    slug: "explicador",
    categoria: "educacion",
    ruta: "artefactos/educacion/explicador/",
    icono: "🧠",
    color: "var(--cat-educacion)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Explicador de conceptos",
    nombre_en: "Concept Explainer",
    desc_es: "Cualquier concepto, explicado con claridad total.",
    desc_en: "Any concept, explained with total clarity.",
    desc_larga_es: "El Explicador de Conceptos descompone cualquier idea compleja en explicaciones claras y accesibles. Desde física cuántica hasta blockchain, la IA adapta el nivel de profundidad a tu conocimiento previo. Usa analogías, ejemplos del mundo real y progresión gradual.",
    desc_larga_en: "The Concept Explainer breaks down any complex idea into clear, accessible explanations. From quantum physics to blockchain, the AI adapts the depth level to your prior knowledge. Uses analogies, real-world examples and gradual progression.",
    features_es: ["Adaptado a tu nivel de conocimiento", "Analogías y ejemplos reales", "Progresión gradual de complejidad", "Bilingüe ES/EN"],
    features_en: ["Adapted to your knowledge level", "Analogies and real examples", "Gradual complexity progression", "Bilingual ES/EN"],
    paso_es: "Introduce un concepto para recibir una explicación clara",
    paso_en: "Enter a concept to receive a clear explanation",
    estado: "live"
  },
  {
    id: "flashcards",
    slug: "flashcards",
    categoria: "educacion",
    ruta: "artefactos/educacion/flashcards/",
    icono: "🃏",
    color: "var(--cat-educacion)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Generador de flashcards",
    nombre_en: "Flashcard Generator",
    desc_es: "Convierte cualquier texto en tarjetas de repaso.",
    desc_en: "Turn any text into study flashcards.",
    desc_larga_es: "El Generador de Flashcards convierte cualquier texto — apuntes, artículos, capítulos — en tarjetas de estudio interactivas con pregunta y respuesta. La IA identifica los conceptos clave y formula preguntas que maximizan la retención. Estudio activo potenciado por IA.",
    desc_larga_en: "The Flashcard Generator converts any text — notes, articles, chapters — into interactive study cards with question and answer. The AI identifies key concepts and formulates questions that maximize retention. AI-powered active study.",
    features_es: ["Generación automática de preguntas", "Tarjetas interactivas flip", "Funciona con cualquier texto", "Bilingüe ES/EN"],
    features_en: ["Automatic question generation", "Interactive flip cards", "Works with any text", "Bilingual ES/EN"],
    paso_es: "Pega un texto para generar tarjetas de estudio",
    paso_en: "Paste text to generate study cards",
    estado: "live"
  },
  {
    id: "tutor-socratico",
    slug: "tutor-socratico",
    categoria: "educacion",
    ruta: "artefactos/educacion/tutor-socratico/",
    icono: "🏛️",
    color: "var(--cat-educacion)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Tutor socrático",
    nombre_en: "Socratic Tutor",
    desc_es: "Aprende respondiendo preguntas, no leyendo respuestas.",
    desc_en: "Learn by answering questions, not reading answers.",
    desc_larga_es: "El Tutor Socrático te guía al conocimiento a través de preguntas, nunca dándote la respuesta directamente. Elige un tema y el tutor formulará preguntas cada vez más profundas que te llevarán a descubrir los conceptos por ti mismo. El método más antiguo y efectivo de enseñanza.",
    desc_larga_en: "The Socratic Tutor guides you to knowledge through questions, never giving you the answer directly. Choose a topic and the tutor will ask increasingly deep questions that will lead you to discover concepts yourself. The oldest and most effective teaching method.",
    features_es: ["Aprendizaje por descubrimiento guiado", "Preguntas progresivamente más profundas", "Método socrático auténtico", "Bilingüe ES/EN"],
    features_en: ["Guided discovery learning", "Progressively deeper questions", "Authentic Socratic method", "Bilingual ES/EN"],
    paso_es: "Elige un tema y responde a las preguntas del tutor",
    paso_en: "Choose a topic and answer the tutor's questions",
    estado: "live"
  },
  {
    id: "quiz",
    slug: "quiz-adaptativo",
    categoria: "educacion",
    ruta: "artefactos/educacion/quiz-adaptativo/",
    icono: "❓",
    color: "var(--cat-educacion)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Quiz adaptativo",
    nombre_en: "Adaptive Quiz",
    desc_es: "El nivel se adapta a tus respuestas en tiempo real.",
    desc_en: "Difficulty adapts to your answers in real time.",
    desc_larga_es: "El Quiz Adaptativo genera preguntas cuya dificultad se ajusta en tiempo real según tus aciertos y errores. Elige cualquier tema — la IA creará un examen personalizado que siempre te mantiene en tu zona de aprendizaje óptimo. Con explicaciones para cada respuesta.",
    desc_larga_en: "The Adaptive Quiz generates questions whose difficulty adjusts in real time based on your hits and misses. Choose any topic — the AI will create a personalized test that always keeps you in your optimal learning zone. With explanations for each answer.",
    features_es: ["Dificultad adaptativa en tiempo real", "Cualquier tema", "Explicaciones por respuesta", "Bilingüe ES/EN"],
    features_en: ["Real-time adaptive difficulty", "Any topic", "Explanations per answer", "Bilingual ES/EN"],
    paso_es: "Elige un tema y responde preguntas adaptativas",
    paso_en: "Choose a topic and answer adaptive questions",
    estado: "live"
  },
  {
    id: "jerga-tecnica",
    slug: "jerga-tecnica",
    categoria: "educacion",
    ruta: "artefactos/educacion/jerga-tecnica/",
    icono: "🔤",
    color: "var(--cat-educacion)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Traductor de jerga técnica",
    nombre_en: "Tech Jargon Translator",
    desc_es: "Sin jerga. Solo el significado real.",
    desc_en: "No jargon. Just the real meaning.",
    desc_larga_es: "El Traductor de Jerga Técnica convierte terminología especializada en lenguaje claro y cotidiano. Pega un texto lleno de jerga de cualquier campo — medicina, derecho, tecnología, finanzas — y recibe la misma información en un lenguaje que cualquier persona puede entender.",
    desc_larga_en: "The Tech Jargon Translator converts specialized terminology into clear, everyday language. Paste a text full of jargon from any field — medicine, law, technology, finance — and receive the same information in language anyone can understand.",
    features_es: ["Funciona con jerga de cualquier campo", "Mantiene el significado original", "Explicaciones contextuales", "Bilingüe ES/EN"],
    features_en: ["Works with jargon from any field", "Preserves original meaning", "Contextual explanations", "Bilingual ES/EN"],
    paso_es: "Pega texto con jerga técnica para obtener lenguaje claro",
    paso_en: "Paste text with tech jargon to get plain language",
    estado: "live"
  },
  {
    id: "simulador-entrevista",
    slug: "simulador-entrevista",
    categoria: "educacion",
    ruta: "artefactos/educacion/simulador-entrevista/",
    icono: "🎯",
    color: "var(--cat-educacion)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Simulador de entrevista",
    nombre_en: "Interview Simulator",
    desc_es: "Practica entrevistas con feedback inmediato.",
    desc_en: "Practice interviews with immediate feedback.",
    desc_larga_es: "El Simulador de Entrevista te prepara para entrevistas de trabajo con práctica realista. Indica el puesto y la empresa, y la IA te hará preguntas como un entrevistador real. Después de cada respuesta, recibes feedback inmediato con sugerencias de mejora y puntuación.",
    desc_larga_en: "The Interview Simulator prepares you for job interviews with realistic practice. Indicate the position and company, and the AI will ask you questions like a real interviewer. After each answer, you receive immediate feedback with improvement suggestions and scoring.",
    features_es: ["Preguntas realistas por puesto", "Feedback inmediato por respuesta", "Puntuación y sugerencias de mejora", "Bilingüe ES/EN"],
    features_en: ["Realistic position-specific questions", "Immediate per-answer feedback", "Scoring and improvement suggestions", "Bilingual ES/EN"],
    paso_es: "Indica el puesto y practica con preguntas de entrevista",
    paso_en: "Indicate the position and practice with interview questions",
    estado: "live"
  },
  {
    id: "mentor-idiomas",
    slug: "mentor-idiomas",
    categoria: "educacion",
    ruta: "artefactos/educacion/mentor-idiomas/",
    icono: "🗺️",
    color: "var(--cat-educacion)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Mentor de idiomas",
    nombre_en: "Language Mentor",
    desc_es: "Conversa y aprende cualquier idioma sin salir.",
    desc_en: "Converse and learn any language without leaving.",
    desc_larga_es: "El Mentor de Idiomas te permite practicar cualquier idioma a través de conversaciones naturales con IA. Elige tu nivel, el idioma objetivo y un tema de conversación. El mentor corrige tus errores en tiempo real y te enseña vocabulario y gramática de forma natural.",
    desc_larga_en: "The Language Mentor lets you practice any language through natural conversations with AI. Choose your level, target language and conversation topic. The mentor corrects your mistakes in real time and teaches vocabulary and grammar naturally.",
    features_es: ["Conversación natural en cualquier idioma", "Corrección de errores en tiempo real", "Adaptado a tu nivel", "Bilingüe ES/EN"],
    features_en: ["Natural conversation in any language", "Real-time error correction", "Adapted to your level", "Bilingual ES/EN"],
    paso_es: "Elige un idioma, tu nivel y empieza a conversar",
    paso_en: "Choose a language, your level and start conversing",
    estado: "live"
  },
  {
    id: "resumen-academico",
    slug: "resumen-academico",
    categoria: "educacion",
    ruta: "artefactos/educacion/resumen-academico/",
    icono: "📚",
    color: "var(--cat-educacion)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Resumen académico",
    nombre_en: "Academic Summary",
    desc_es: "Papers y artículos académicos en lenguaje humano.",
    desc_en: "Academic papers in human language.",
    desc_larga_es: "El Resumen Académico traduce papers, artículos científicos y documentos académicos a un lenguaje claro y comprensible. Extrae la tesis principal, la metodología, los hallazgos clave y las implicaciones, todo en un formato que no requiere doctorado para entender.",
    desc_larga_en: "The Academic Summary translates papers, scientific articles and academic documents into clear, understandable language. Extracts the main thesis, methodology, key findings and implications, all in a format that doesn't require a PhD to understand.",
    features_es: ["Extracción de tesis y hallazgos clave", "Metodología explicada claramente", "Implicaciones en lenguaje accesible", "Bilingüe ES/EN"],
    features_en: ["Main thesis and key findings extraction", "Clearly explained methodology", "Implications in accessible language", "Bilingual ES/EN"],
    paso_es: "Pega un paper o artículo académico para resumirlo",
    paso_en: "Paste a paper or academic article to summarize it",
    estado: "live"
  },
  {
    id: "casos-practicos",
    slug: "casos-practicos",
    categoria: "educacion",
    ruta: "artefactos/educacion/casos-practicos/",
    icono: "💼",
    color: "var(--cat-educacion)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Generador de casos prácticos",
    nombre_en: "Case Study Generator",
    desc_es: "Casos reales para aprender cualquier disciplina.",
    desc_en: "Real cases to learn any discipline.",
    desc_larga_es: "El Generador de Casos Prácticos crea escenarios realistas para aprender cualquier disciplina mediante la práctica. Indica el tema — derecho, medicina, empresa, ingeniería — y la IA generará un caso con contexto, datos, preguntas guía y resolución. Aprender haciendo.",
    desc_larga_en: "The Case Study Generator creates realistic scenarios to learn any discipline through practice. Indicate the topic — law, medicine, business, engineering — and the AI will generate a case with context, data, guiding questions and resolution. Learning by doing.",
    features_es: ["Casos realistas con datos", "Preguntas guía para análisis", "Resolución incluida", "Bilingüe ES/EN"],
    features_en: ["Realistic cases with data", "Guiding questions for analysis", "Resolution included", "Bilingual ES/EN"],
    paso_es: "Elige una disciplina para generar un caso práctico",
    paso_en: "Choose a discipline to generate a case study",
    estado: "live"
  },
  {
    id: "debate-socratico",
    slug: "debate-socratico",
    categoria: "educacion",
    ruta: "artefactos/educacion/debate-socratico/",
    icono: "⚔️",
    color: "var(--cat-educacion)",
    categoria_schema: "EducationalApplication",
    nombre_es: "Debate Socrático",
    nombre_en: "Socratic Debate",
    desc_es: "Dos tesis enfrentadas con análisis de falacias.",
    desc_en: "Two opposing theses with fallacy analysis.",
    desc_larga_es: "El Debate Socrático genera debates estructurados con dos tesis enfrentadas sobre cualquier tema. Cada lado presenta argumentos con peso clasificado (fuerte, medio, débil), se identifican falacias y se generan preguntas de examen. La herramienta perfecta para pensamiento crítico.",
    desc_larga_en: "The Socratic Debate generates structured debates with two opposing theses on any topic. Each side presents arguments with classified weight (strong, medium, weak), fallacies are identified and exam questions are generated. The perfect tool for critical thinking.",
    features_es: ["Argumentos con peso clasificado", "Detección de falacias", "Preguntas de examen generadas", "Bilingüe ES/EN"],
    features_en: ["Arguments with classified weight", "Fallacy detection", "Generated exam questions", "Bilingual ES/EN"],
    paso_es: "Introduce un tema controvertido para generar el debate",
    paso_en: "Enter a controversial topic to generate the debate",
    estado: "live"
  }
];

// Helpers
export function getCatalogo() { return CATALOGO; }
export function getBySlug(slug) { return CATALOGO.find(a => a.slug === slug); }
export function getByCategoria(cat) { return CATALOGO.filter(a => a.categoria === cat); }
export function getLive() { return CATALOGO.filter(a => a.estado === 'live'); }
export function getCategorias() { return ['diversion', 'productividad', 'research', 'creatividad', 'educacion']; }
